### ISSUE TITLE
Regarding the `bits` function in the talk

### ISSUE THREAD

**Issue by BowenLiu92** [brandon-rhodes/pycon2010-mighty-dictionary#2]
Hi Mr. Rhodes,

Sorry if this is a naive question. I am following your lecture along but I got stumped in one of the first slides. For your line of code: 
```for key in 'Monty', 3.1415, (2, 6, 4):
    print(bits(hash(key)), key)```
Apparently for Python 3.7, bits is not a built-in function anymore. I tried using `bin` but didn't get the same results. Googling "Python 2.7 bits function" didn't get me anything useful at all. 

I am sure this won't affect the whole lecture, but still am curious to know. 

Thanks.

**Comment by brandon-rhodes** [comment]
There are several helper functions mentioned in the talk and included in the code for the talk — if you try searching the code for "bits", this function will hopefully come up:

https://github.com/brandon-rhodes/pycon2010-mighty-dictionary/blob/master/figures/_dictdraw.py#L12

**Comment by BowenLiu92** [comment]
Thanks a lot. I do see it. Sorry I am not familiar enough with github to thoroughly navigate to what is needed. Appreciate it!
